version: "3.8"


services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
  web:
    build:
      context: .
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
#    command: gunicorn SheepFishVPN.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - 8050:8000
    environment:
      SQL_HOST: "postgres"
    env_file: .env
    depends_on:
      - postgres
  postgres:
    image: postgres:13-alpine
    ports:
      - "5433:5432"
    env_file: .env
#  mitmweb:
#    image: mitmproxy/mitmproxy
#    tty: true
#    ports:
#      - 8080:8080
#      - 8081:8081
#    command: mitmweb --web-iface 0.0.0.0 --mode reverse:http://web/
#  mitmdump:
#    image: mitmproxy/mitmproxy
#    command: mitmdump -nC /home/mitmproxy/flows
#    depends_on:
#      - nginx
#    volumes:
#      - ./mitmproxy:/home/mitmproxy/