# Generated by Django 4.2.7 on 2023-11-19 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_site_name_alter_site_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
